services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: chatcesu
      POSTGRES_PASSWORD: chatcesu123
      POSTGRES_DB: chatcesu
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
